Ww leaflet
weweb-assets/ww-openstreetmap-leaflet pull request #2
Opened 2024-02-15 23:36 UTC by kevinbarfleur

2024-02-19 14:21 UTC, AlexisJC approved these changes

2024-02-19 14:24 UTC, Dams-d approved these changes

2024-02-19 16:23 UTC, Dams-d requested changes
remove  console.log and use same functions for options

2024-02-19 16:23 UTC, Dams-d commented on src/use/useLeafletMap.js
> +      console.log("data ⚠️", {
remove log

2024-02-20 09:43 UTC, Dams-d approved these changes

2024-02-20 09:44 UTC, merged